### PR TITLE
Mention not filing issues to top of README

### PR DESCRIPTION
**Pull request by mikehaas763**
I think this is worth a try to cut down even more on people filing issues here. That or maybe you can influence GH to add the functionality needed to prevent non-collaborators from posting issues?

### CODE REVIEW

**Comment by Eilon** [comment]
@mikehaas763 the readme already mentions it I think fairly clearly. I'm guessing people aren't reading the readme at all (not too surprising, of course), so adding more warnings probably won't help :crying_cat_face:

**Comment by mikehaas763** [comment]
@Eilon I really disagree because I've been watching this repo for about a month and have already had more notifications than I can remember regarding issues that shouldn't have been filed here. The readme currently doesn't mention that you should not report issues here. It implies it indirectly by suggesting you file issues elsewhere.

The other thing is the location of this text may make it more obvious because it's at the top of the readme.

**Comment by Daniel15** [comment]
It's unfortunate that Github lacks basic issues that literally *every other issue tracker* has. One such feature is permission groups and granular permissions, to make it so that only approved people can submit issues in this repo.

As I've mentioned in the past, it seems strange to use Github issues in this way... They're really not designed for scenarios like this, and as a result they handle it extremely poorly.

**Comment by Eilon** [comment]
Fair enough, I made a slightly different change: https://github.com/aspnet/Announcements/blob/master/README.md

I agree it would be nice if GitHub had more granular permissions. I think overall the Announcements repo has worked fairly well, despite its shortcomings.

**Comment by mikehaas763** [comment]
@Daniel15 I'm in agreement with you except that it's kind of hard to argue against using a repo+issues for this use case when it seems to work so well (aside from the issue posting permissions problem).

@Eilon Thanks for that. Now to wait and see if it works :smile:

**Comment by Michael-DST** [comment]
+1 to @Daniel15's sentiments. FWIW, after what I have seen from Visual Studio Team Services today during the [Connect 2015 keynote](https://channel9.msdn.com/), I think it's fair to say that there should start being more integration between GitHub and VSTS to get better collaborative workflow solutions.  Because... yeah, GitHub is lacking.  Sorely. :P

**Pull request closed without merging**
